#!/bin/bash

#
# SS7 HA Gateway Entrypoint Script
#

set -e

echo "======================================"
echo "SS7 HA Gateway - Starting Node $NODE_ID"
echo "======================================"

# Function to wait for service
wait_for_service() {
    local host=$1
    local port=$2
    local service=$3
    
    echo "Waiting for $service at $host:$port..."
    while ! nc -z "$host" "$port"; do
        sleep 1
    done
    echo "$service at $host:$port is available"
}

# --- Generate ss7-ha-gateway.properties from Environment Variables ---
echo "Generating /app/config/ss7-ha-gateway.properties from environment variables..."
cat > /app/config/ss7-ha-gateway.properties <<EOF
# SS7 HA Gateway Configuration
# Generated by entrypoint.sh at $(date)

#
# Redis Configuration
#
redis.cluster.nodes=${REDIS_CLUSTER_NODES:-localhost:7000}
redis.dialog.ttl=${REDIS_DIALOG_TTL:-3600}
redis.persist.dialogs=${REDIS_PERSIST_DIALOGS:-true}

#
# Kafka Configuration (if used, currently NATS)
#
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
kafka.client.id=${KAFKA_CLIENT_ID:-ss7-ha-gateway-node-1}
kafka.topic.prefix=${KAFKA_TOPIC_PREFIX:-ss7.}
kafka.publish.enabled=${KAFKA_PUBLISH_ENABLED:-false}

#
# M3UA Configuration
#
m3ua.name=${M3UA_NAME:-M3UA-STACK}
m3ua.sctp.server.host=${M3UA_SCTP_SERVER_HOST:-0.0.0.0}
m3ua.sctp.server.port=${M3UA_SCTP_SERVER_PORT:-2905}
m3ua.sctp.client.host=${M3UA_SCTP_CLIENT_HOST:-127.0.0.1}
m3ua.sctp.client.port=${M3UA_SCTP_CLIENT_PORT:-2906}

m3ua.local.pc=${SS7_LOCAL_PC:-1}
m3ua.remote.pc=${SS7_DPC:-2}
m3ua.local.ssn=${SS7_LOCAL_SSN:-8}
m3ua.remote.ssn=${SS7_REMOTE_SSN:-8}
m3ua.routing.context=${SS7_ROUTING_CONTEXT:-100}
m3ua.network.indicator=${SS7_NI:-2}


#
# SCCP Configuration
#
sccp.name=${SCCP_NAME:-SCCP-STACK}
sccp.local.pc=${SS7_LOCAL_PC:-1}
sccp.remote.pc=${SS7_DPC:-2}
sccp.local.ssn=${SS7_LOCAL_SSN:-8}
sccp.remote.ssn=${SS7_REMOTE_SSN:-8}
sccp.local.gt=${SCCP_LOCAL_GT:-123456789}
sccp.network.indicator=${SS7_NI:-2}
sccp.routeOnGT=${SCCP_ROUTE_ON_GT:-true}


#
# TCAP Configuration
#
tcap.name=${TCAP_NAME:-TCAP-STACK}
tcap.dialog.idle.timeout=${TCAP_DIALOG_IDLE_TIMEOUT:-60000}
tcap.invoke.timeout=${TCAP_INVOKE_TIMEOUT:-30000}
tcap.max.dialogs=${TCAP_MAX_DIALOGS:-5000}

#
# MAP Configuration
#
map.name=${MAP_NAME:-MAP-STACK}
map.version=${MAP_VERSION:-MAP_V3}

#
# Monitoring Configuration
#
monitoring.prometheus.enabled=${MONITORING_PROMETHEUS_ENABLED:-true}
monitoring.prometheus.port=${MONITORING_PROMETHEUS_PORT:-9090}
monitoring.health.check.interval=${MONITORING_HEALTH_CHECK_INTERVAL:-30000}

#
# Logging Configuration
#
logging.level=${LOGGING_LEVEL:-INFO}
logging.file=${LOGGING_FILE:-/var/log/ss7-ha-gateway/gateway.log}

#
# NATS Configuration
#
nats.server.url=${NATS_URL:-nats://localhost:4222}
nats.queue.group=${NATS_QUEUE_GROUP:-ss7-gateway-group-v2}
events.publish.enabled=${EVENTS_PUBLISH_ENABLED:-true}
dialog.persist.enabled=${DIALOG_PERSIST_ENABLED:-true}
dialog.ttl.seconds=${DIALOG_TTL_SECONDS:-600}

EOF
echo "--- Generated ss7-ha-gateway.properties ---"
cat /app/config/ss7-ha-gateway.properties
echo "-------------------------------------------"

# Wait for Redis cluster to be ready (if configured)
if [[ "${REDIS_CLUSTER_NODES}" == *"localhost"* || -z "${REDIS_CLUSTER_NODES}" ]]; then
    echo "Redis cluster nodes not explicitly set or set to localhost, skipping wait."
else
    for node in $(echo $REDIS_CLUSTER_NODES | tr ',' ' '); do
        host=$(echo $node | cut -d':' -f1)
        port=$(echo $node | cut -d':' -f2)
        wait_for_service "$host" "$port" "Redis"
    done
fi

# Wait for Kafka to be ready (if configured)
if [[ "${KAFKA_BOOTSTRAP_SERVERS}" == *"localhost"* || -z "${KAFKA_BOOTSTRAP_SERVERS}" ]]; then
    echo "Kafka bootstrap servers not explicitly set or set to localhost, skipping wait."
else
    for broker in $(echo $KAFKA_BOOTSTRAP_SERVERS | tr ',' ' '); do
        host=$(echo $broker | cut -d':' -f1)
        port=$(echo $broker | cut -d':' -f2)
        wait_for_service "$host" "$port" "Kafka"
    done
fi

# Start application
echo "Starting SS7 HA Gateway..."
exec java $JAVA_OPTS \
    -Dconfig.file=/app/config/ss7-ha-gateway.properties \
    -Dnode.id=$NODE_ID \
    -Dnats.server.url=$NATS_URL \
    -jar ss7-ha-gateway.jar